### ISSUE TITLE
训练代码报错

### ISSUE THREAD

**Issue by salanzewei** [yuedajiong/super-ai-vision-stereo-world-generate-triposr#5]
十分感谢您的开源，我是一个深度学习领域的新手，正在学习您的代码。
执行`infer`代码没有问题，执行`train`代码报以下错误，报错时x的0维度变为了0，我不太明白为什么会变为0，要如何修改？
```bash
torch.Size([8192, 120])
torch.Size([8192, 120])
torch.Size([0, 120])
Traceback (most recent call last):
  File "e:\Projects\super-ai-vision-stereo-world-generate-triposr-main\superv.py", line 340, in <module>
    main()
  File "e:\Projects\super-ai-vision-stereo-world-generate-triposr-main\superv.py", line 331, in main
    train(
  File "e:\Projects\super-ai-vision-stereo-world-generate-triposr-main\superv.py", line 311, in train
    mesh = model.extract_mesh(scene_codes)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Projects\super-ai-vision-stereo-world-generate-triposr-main\network.py", line 80, in extract_mesh
    color = self.renderer.query_triplane(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Projects\super-ai-vision-stereo-world-generate-triposr-main\network_nerf_renderer.py", line 131, in query_triplane
    net_out = chunk_batch(_query_chunk, self.chunk_size, positions)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Projects\super-ai-vision-stereo-world-generate-triposr-main\network_nerf_renderer.py", line 48, in chunk_batch
    out_chunk = func(
                ^^^^^
  File "e:\Projects\super-ai-vision-stereo-world-generate-triposr-main\network_nerf_renderer.py", line 108, in _query_chunk
    net_out: Dict[str, torch.Tensor] = decoder(out)
                                       ^^^^^^^^^^^^
  File "D:\Users\yu.zewei\Anaconda3\envs\triposr_py311\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Projects\super-ai-vision-stereo-world-generate-triposr-main\network_nerf_decoder.py", line 49, in forward
    features = self.layers(x).reshape(*x.shape[:-1], -1)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1] because the unspecified dimension size -1 can be any value and is ambiguous
```

**Comment by salanzewei** [comment]
这个问题是我将`torchmcubes`替换为`pymcubes`导致的，出于某种原因`pymcubes`可以在推理时正常工作，但训练时`marching_cubes`无法计算出`v_pos`(值为空)
